FROM python:3.10-alpine

WORKDIR /app

COPY requirements.txt /app/requirements.txt

# Install dependencies
RUN pip install --no-cache-dir --upgrade -r /app/requirements.txt

# Copy source code
COPY . /app

# Test application
RUN pytest -v
